### ISSUE TITLE
KickAssets in HTMLEditor insert media form

### ISSUE THREAD

**Issue by sheadawson** [unclecheese/silverstripe-kickassets#12]
Hey Mr Cheese,

I have a potential client who is really keen to see the KickAssets file browser UI made available in the WYSIWYG insert media form and UploadField "From Files" form. I'm going have a good look at it over the next couple of days to provide a quote. 

Do you have any advice or thoughts to offer someone attempting such an endeavour? Any ideas around how you'd like to see this implemented or anything that I should consider?

Any input appreciated!

**Comment by unclecheese** [comment]
Hi, Shea,

Interesting timing. I'm going to be redoing this module soon, and one of the primary features will be a public JavaScript API, so that any module can use it. Imagine something like this:

```js
KickAssets.requestFile(function (fileID) {
    myModule.setFile(fileID);
});
```

So that would pave a clear path for you to implement it in the WYSIWYG editor. You'd only have to write the integration.  If you can wait for me to do that, you'll have a really easy time, but if not, it's going to be a fair amount of work, and I wouldn't even know where to start.

Maybe you can tell your client to be a bit patient? I don't have a time frame right now, but I always have a pet project I'm working on, and KA will be front-and-centre starting within the next week or so.

**Comment by MattyBalaam** [comment]
Great news.

**Comment by hailwood** [comment]
HEy @unclecheese great to see this is released now, any suggestions on where to start with replacing the standard filepicker ui now? Ideally I'm looking for a way to keep it compatible with existing modules like sortablefile.

Don't mind doing a bit of work on it, just not sure where to start!

**Comment by unclecheese** [comment]
This is now in the 3.1 release.
