### ISSUE TITLE
Cannot edit additional properties on files.

### ISSUE THREAD

**Issue by hailwood** [unclecheese/silverstripe-kickassets#20]
E.g. We have a "SeoTitle" field that we add to Image via an extension.
We have another class "LinkedImage" which has_one Link (https://github.com/sheadawson/silverstripe-linkable).

With the standard File Manager we can edit these additional fields/relations as well. However with kickassets the form seems fixed, combining this issue with using FileAttachmentField instead of UploadField we lose any capability to edit these fields.

**Comment by unclecheese** [comment]
Yeah, there isn't a clear solution to this problem yet, unfortunately.

**Comment by jonom** [comment]
Hey @unclecheese I'm dying to use this module in production but unfortunately not being able to access the detailed edit form is a deal breaker for me. I had a quick look to see if I could do anything about this but I see what you mean, since this is all React based it doesn't look like this is something that could be fixed until SS4 is out and we have a solution for this kind of problem baked in to the framework.

I was wondering for a short-term SS3 fix if it might be worth adding a 'More options' link to the edit form that takes you through to the regular editing form at `/admin/assets/EditForm/field/File/item/{$FileID}/edit`?

Then we could have our cake and eat it too.

Example:

![options](https://cloud.githubusercontent.com/assets/1079425/13827237/a2d5334a-eb78-11e5-8373-23e4c6215464.png)

**Comment by chillu** [comment]
FYI, this is the framework approach we'll take for SS4: https://github.com/silverstripe/silverstripe-framework/issues/4938

**Comment by jonom** [comment]
Thanks @chillu, bit over my head for now :sweat_smile: 

@unclecheese If I develop a PR for proposal above would you be interested?

**Comment by unclecheese** [comment]
Honestly we're so close to reinventing the wheel on this one, I think it would be wasteful to build it for KickAssets. In SS4 we should have some semblance of this API, correct, @chillu ?

Once we have that, we can either build on it, or maybe even use it in its entirety. That is, if this module isn't completely deprecated by the awesomeness of the new AssetAdmin. :-)

Ideally, the form field schema stuff goes into a module that works in 3.x, so we could plug it in and offer backward compatibility.

**Comment by jonom** [comment]
Oh yeah - sorry I wasn't talking about developing that (no way!) I'm just talking about adding a ['More options'](https://github.com/unclecheese/silverstripe-kickassets/issues/20#issuecomment-197526879) link that takes you to the regular Assets Admin interface for that file. Maybe it could be configurable whether it's enabled or not so it's not cluttering up the interface if it's not needed?
