### ISSUE TITLE
Additional fields added to File via a data extension are not visible

### ISSUE THREAD

**Issue by michalkleiner** [unclecheese/silverstripe-kickassets#77]
The subject should be clear enough.

I'd put this down to kickassets only replicating the default functionality, not knowing anything about the underlying 'editform'.

**Comment by unclecheese** [comment]
Yeah, this has been brought up many times. It's just an accepted cost of using the module, because there's no simple way to create that form with client side technology without the FormSchema API (SS4).

Someone a while back added a feature that lets you jump out to the edit window in the standard asset admin. I think that is just going to have to do.
